-- Incremental append into facts_realtime_logs from vw_master_log_latest.
-- Replace PROJECT if you use a different GCP project id (e.g. alubee-prod).
--
-- Grain: rows are inserted only when (device_id, publish_time, measurement)
-- is not already present in the mart. Adjust the ON clause if your table
-- uses a different uniqueness rule (e.g. drop measurement if always one row per event).

MERGE `alubee-prod.alubee_production_marts.facts_realtime_logs` AS T
USING (
  SELECT
    publish_time,
    publish_time_ist,
    device_id,
    measurement,
    value,
    partNo,
    item_code,
    uptime_ms,
    boot_count,
    reset_reason,
    scheduled_reset_morning_ok,
    scheduled_restart_morning_ok,
    scheduled_reset_evening_ok,
    scheduled_restart_evening_ok,
    wifi_status,
    wifi_rssi_dbm,
    wifi_ip,
    wifi_mac,
    wifi_disconnect_count,
    wifi_reconnect_count,
    shot_count,
    idle_measurement_code,
    machine_status,
    free_heap_bytes,
    min_free_heap_bytes,
    loop_time_ms_avg,
    loop_time_ms_max,
    error_code,
    error_source,
    error_msg,
    last_error_epoch,
    error_count_today,
    gpio32_adc_raw,
    gpio32_voltage_v,
    chip_temp_c,
    i2c_lcd_0x27_present,
    i2c_lcd_probe_fail_count,
    i2c_garbage_suspected,
    unit,
    machine_type,
    CURRENT_TIMESTAMP() AS inserted_at
  FROM `alubee-prod.alubee_production_intermediate.vw_master_log_latest`
) AS S
ON T.device_id = S.device_id
  AND T.publish_time = S.publish_time
  AND T.measurement = S.measurement
WHEN NOT MATCHED BY TARGET THEN
  INSERT (
    publish_time,
    publish_time_ist,
    device_id,
    measurement,
    value,
    partNo,
    item_code,
    uptime_ms,
    boot_count,
    reset_reason,
    scheduled_reset_morning_ok,
    scheduled_restart_morning_ok,
    scheduled_reset_evening_ok,
    scheduled_restart_evening_ok,
    wifi_status,
    wifi_rssi_dbm,
    wifi_ip,
    wifi_mac,
    wifi_disconnect_count,
    wifi_reconnect_count,
    shot_count,
    idle_measurement_code,
    machine_status,
    free_heap_bytes,
    min_free_heap_bytes,
    loop_time_ms_avg,
    loop_time_ms_max,
    error_code,
    error_source,
    error_msg,
    last_error_epoch,
    error_count_today,
    gpio32_adc_raw,
    gpio32_voltage_v,
    chip_temp_c,
    i2c_lcd_0x27_present,
    i2c_lcd_probe_fail_count,
    i2c_garbage_suspected,
    unit,
    machine_type,
    inserted_at
  )
  VALUES (
    S.publish_time,
    S.publish_time_ist,
    S.device_id,
    S.measurement,
    S.value,
    S.partNo,
    S.item_code,
    S.uptime_ms,
    S.boot_count,
    S.reset_reason,
    S.scheduled_reset_morning_ok,
    S.scheduled_restart_morning_ok,
    S.scheduled_reset_evening_ok,
    S.scheduled_restart_evening_ok,
    S.wifi_status,
    S.wifi_rssi_dbm,
    S.wifi_ip,
    S.wifi_mac,
    S.wifi_disconnect_count,
    S.wifi_reconnect_count,
    S.shot_count,
    S.idle_measurement_code,
    S.machine_status,
    S.free_heap_bytes,
    S.min_free_heap_bytes,
    S.loop_time_ms_avg,
    S.loop_time_ms_max,
    S.error_code,
    S.error_source,
    S.error_msg,
    S.last_error_epoch,
    S.error_count_today,
    S.gpio32_adc_raw,
    S.gpio32_voltage_v,
    S.chip_temp_c,
    S.i2c_lcd_0x27_present,
    S.i2c_lcd_probe_fail_count,
    S.i2c_garbage_suspected,
    S.unit,
    S.machine_type,
    S.inserted_at
  );
